# Force rebuild - Railway Laravel + Vite Build
[phases.setup]
nixPkgs = ['php82', 'nodejs_20']

[phases.install]
cmds = [
    'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer',
    'php /usr/local/bin/composer install --no-dev --optimize-autoloader',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan storage:link'
]

[start]
cmd = 'php -S 0.0.0.0:${PORT:-8000} -t public' 